### ISSUE TITLE
Error running npm start: '.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by bensgroi** [jhades/ng2-minimal#5]
From the scripts section of package.json, this line looks suspect to me: 
"serve": "./node_modules/.bin/http-server -c-1 ."

Here's the full output of "npm start":

'.' is not recognized as an internal or external command, operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run-script" "watch"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! ng2-minimal@1.0.0 watch: `./node_modules/.bin/nodemon -V -w src --ext ".ts" --exec "npm run build-app"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-minimal@1.0.0 watch script ' ./node_modules/.bin/node mon -V -w src --ext ".ts" --exec "npm run build-app"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-minimal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!      ./node_modules/.bin/nodemon -V -w src --ext ".ts" --exec "npm run build-app"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-minimal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-minimal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users***\Source\GitHub\ng2-minimal\npm-debug.log
ERROR: watch: None-Zero Exit(1);

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! ng2-minimal@1.0.0 start: `npm-run-all build-ts build-lib  -p watch serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-minimal@1.0.0 start script 'npm-run-all build-ts build-lib  -p watch serve '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-minimal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all build-ts build-lib  -p watch serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-minimal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-minimal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users***\Source\GitHub\ng2-minimal\npm-debug.log

**Comment by bensgroi** [comment]
And actually, I removed the trailing "." from the command, and I'm still getting the error.

**Comment by jhades** [comment]
fixed, please update and retry

**Comment by bensgroi** [comment]
@jhades Great, thanks!

**Comment by subashininj6586** [comment]
Creating a new React app in E:\KL University\MSWD\part1.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


> core-js@2.6.12 postinstall E:\KL University\MSWD\part1\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.12.1 postinstall E:\KL University\MSWD\part1\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.12.1 postinstall E:\KL University\MSWD\part1\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall E:\KL University\MSWD\part1\node_modules\ejs
> node ./postinstall.js

+ cra-template@1.1.2
+ react@17.0.2
+ react-dom@17.0.2
+ react-scripts@4.0.3
added 1924 packages from 731 contributors and audited 1927 packages in 146.563s

136 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

my npx create-react-app part1 not completing and its truck here
